#define _Game_Unknown0_Address 0x0E25CD0

#define _Game_CSystem_IntializeEngineModule_Address 0x042F490
#define _Game_CryCreateClassInstance_Address 0x042E720
#define _Game_CBinaryXmlNode_getAttr_Address 0x0491BE0
#define _Game_CreateSystemInterface_Address 0x04286A0

#define _Game_ForceCryAISystemInitialization_Ñondition false

//IScriptSystem
#define _Game_IScriptSystem_BeginPreCachedBuffer_Vtable_Offset 232//Not default
#define _Game_IScriptSystem_PreCacheBuffer_Vtable_Offset 228//Not default
#define _Game_IScriptSystem_CompileBuffer_Vtable_Offset 224//Not default

//IEntitySystem
#define _Game_IEntitySystem_AddSink_Vtable_Offset 92
#define _Game_IEntitySystem_RemoveSink_Vtable_Offset 96
#define _Game_IEntitySystem_GetIEntityPoolManager_Vtable_Offset 140
#define _Game_IEntitySystem_GetEntityIterator_Vtable_Offset 68
#define _Game_IEntitySystem_GetEntityFromPhysics_Vtable_Offset 88

//ICryPak
#define _Game_ICryPak_FindFirst_Vtable_Offset 216
#define _Game_ICryPak_FindNext_Vtable_Offset 220
#define _Game_ICryPak_FindClose_Vtable_Offset 224
#define _Game_ICryPak_FClose_Vtable_Offset 184

//ITimeOfDay
#define _Game_ITimeOfDay_GetTime_Vtable_Offset 24

//IXmlNode
#define _Game_IXmlNode_getAttr_Vtable_Offset 104

//SSystemGlobalEnvironment
#define _Game_SSystemGlobalEnvironment_p3DEngine_Offset_Offset 4
#define _Game_SSystemGlobalEnvironment_pScriptSystem_Offset_Offset 12
#define _Game_SSystemGlobalEnvironment_pPhysicalWorld_Offset_Offset 16
#define _Game_SSystemGlobalEnvironment_pCryPak_Offset_Offset 40
#define _Game_SSystemGlobalEnvironment_pTimer_Offset_Offset 60
#define _Game_SSystemGlobalEnvironment_pGame_Offset_Offset 68
#define _Game_SSystemGlobalEnvironment_pEntitySystem_Offset_Offset 76
#define _Game_SSystemGlobalEnvironment_pConsole_Offset_Offset 80
#define _Game_SSystemGlobalEnvironment_pSystem_Offset_Offset 88
#define _Game_SSystemGlobalEnvironment_pLog_Offset_Offset 100
#define _Game_SSystemGlobalEnvironment_pAISystem_Offset_Offset 96
#define _Game_gEnv 0x1538800

#define _Game_PathOther_EnableReadInDirectory_Address 0x15560C4

#define _Game_PatchDamage_Address -1//0x0FAEB92
#define _Game_SGameHitInfo_SGameHitInfo_Address 0x0EC9240
#define _Game_CGameRules_GetClientHitInfoDamage_Address -1//Not found
#define _Game_CGameRules_AddServerHit_Address 0x0E86800

#define _Game_CGameRules_ProcessServerHit_Address 0x0E86020
#define _Game_CGameRules_GetActorByEntityId_Address 0x0D94180
#define _Game_CActor_GetHealth_Vtable_Offset 96
#define _Game_CGameRules_m_scriptHitInfo_Vtable_Offset 292
#define _Game_CGameRules_CreateScriptHitInfo_Address 0x0D988A0
#define _Game_CGameRules_m_serverStateScript_Vtable_Offset 72
#define _Game_CGameRules_CGameRules_CallScript_Address 0x0E7F190

#define _Game_IConsole_AddCommand_Vtable_Offset 124
#define _Game_IConsoleCmdArgs_GetArg_Vtable_Offset 8
#define _Game_IGame_GetIGameFramework_Vtable_Offset 56
#define _Game_IGameFramework_GetIActorSystem_Vtable_Offset 100
#define _Game_IActorSystem_CreateActorIterator_Vtable_Offset 28
#define _Game_IActorIterator_Next_Vtable_Offset 8
#define _Game_IActor_GetChannelId0_Vtable_Offset 4
#define _Game_IActor_GetChannelId1_Vtable_Offset 52
#define _Game_IGameFramework_GetNetChannel_Vtable_Offset 304
#define _Game_INetChannel_GetProfileId_Vtable_Offset 152
#define _Game_INetChannel_Disconnect_Vtable_Offset 32
#define _Game_IActorIterator_Release_Vtable_Offset 16