#define _Game_Unknown0_Address -1

#define _Game_CSystem_IntializeEngineModule_Address 0x0434360
#define _Game_CryCreateClassInstance_Address 0x04335C0
#define _Game_CBinaryXmlNode_getAttr_Address 0x04970B0
#define _Game_CreateSystemInterface_Address 0x042D3B0

#define _Game_ForceCryAISystemInitialization_Ñondition true

//IScriptSystem
#define _Game_IScriptSystem_BeginPreCachedBuffer_Vtable_Offset 232
#define _Game_IScriptSystem_PreCacheBuffer_Vtable_Offset 228
#define _Game_IScriptSystem_CompileBuffer_Vtable_Offset 224

//IEntitySystem
#define _Game_IEntitySystem_AddSink_Vtable_Offset 96
#define _Game_IEntitySystem_RemoveSink_Vtable_Offset 100
#define _Game_IEntitySystem_GetIEntityPoolManager_Vtable_Offset 144
#define _Game_IEntitySystem_GetEntityIterator_Vtable_Offset 72
#define _Game_IEntitySystem_GetEntityFromPhysics_Vtable_Offset 92

//ICryPak
#define _Game_ICryPak_FindFirst_Vtable_Offset 220
#define _Game_ICryPak_FindNext_Vtable_Offset 224
#define _Game_ICryPak_FindClose_Vtable_Offset 228
#define _Game_ICryPak_FClose_Vtable_Offset 188

//ITimeOfDay
#define _Game_ITimeOfDay_GetTime_Vtable_Offset 28

//IXmlNode
#define _Game_IXmlNode_getAttr_Vtable_Offset 104//Default

//SSystemGlobalEnvironment
#define _Game_SSystemGlobalEnvironment_p3DEngine_Offset_Offset 120
#define _Game_SSystemGlobalEnvironment_pScriptSystem_Offset_Offset 32
#define _Game_SSystemGlobalEnvironment_pPhysicalWorld_Offset_Offset 44
#define _Game_SSystemGlobalEnvironment_pCryPak_Offset_Offset 72
#define _Game_SSystemGlobalEnvironment_pTimer_Offset_Offset 88
#define _Game_SSystemGlobalEnvironment_pGame_Offset_Offset 96
#define _Game_SSystemGlobalEnvironment_pEntitySystem_Offset_Offset 104
#define _Game_SSystemGlobalEnvironment_pConsole_Offset_Offset 92
#define _Game_SSystemGlobalEnvironment_pSystem_Offset_Offset 112
#define _Game_SSystemGlobalEnvironment_pLog_Offset_Offset 128
#define _Game_SSystemGlobalEnvironment_pAISystem_Offset_Offset 124
#define _Game_gEnv 0x15A8720

#define _Game_PathOther_EnableReadInDirectory_Address 0x15C6564
#define _Game_PathOther_Damage_Address 0x10010F2
#define _Game_PathOther_Damage_Address1 0x0EB4E40
